spring:
  profiles:
    active: test
  jpa:
    open-in-view: false
  application:
    name: ms-pagamentos

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka

server:
  port: 0

