

server:
  port: 8761
  application:
    name: ms-eurekaserver

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
